name = "BooleanSatisfiability"
uuid = "160ab843-0bc6-4ba4-9585-b7478b70f443"
authors = ["Emi Soroka"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
