name: Workflow for Codecov example-julia
on:
push:
  branches:
    - main
pull_request:
  types: [opened, synchronize, reopened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup z3
        run: sudo apt-get -y install z3
      
      - name: Set up Julia 1.8.0
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.8.0"
      
      - name: Run tests
        uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3 
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: lcov.info  # https://github.com/julia-actions/julia-processcoverage