name: docs
# https://github.com/julia-actions/julia-docdeploy
on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - main

jobs:
  Documenter:
      permissions:
        contents: write
      name: Documentation
      runs-on: ubuntu-latest
      steps:
        - name: Setup z3
          run: sudo apt-get -y install z3
        - name: Setup cvc5
          run: curl -o /usr/local/bin/cvc5 -L https://github.com/cvc5/cvc5/releases/latest/download/cvc5-Linux && chmod +x /usr/local/bin/cvc5
        - uses: actions/checkout@v4
        - uses: julia-actions/julia-buildpkg@v1
        - uses: julia-actions/julia-docdeploy@v1
          env:
            GITHUB_TOKEN: ${{ secrets.DOCS_GITHUB_TOKEN }}
            JULIA_DEBUG: "Documenter"
