# https://github.com/codecov/example-julia/blob/main/.github/workflows/ci.yml
name: Workflow for Codecov example-julia
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Julia 1.8.0
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.8.0"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3 
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info  # https://github.com/julia-actions/julia-processcoverage
          fail_ci_if_error: false
          verbose: true