# https://github.com/codecov/example-julia/blob/main/.github/workflows/ci.yml
name: Workflow for Codecov example-julia
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Julia 1.8.0
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.8.0"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          fail_ci_if_error: false
          verbose: true